### PR TITLE
Add OpenSSH Article and Cover Image 2

### PR DESCRIPTION
**Pull request by Menmarin**

### CODE REVIEW

**Comment by vpetersson** [comment]
@Menmarin did you verify that this renders correct locally?

**Comment by Menmarin** [comment]
> 
> 
> @Menmarin did you verify that this renders correct locally?

Yeah, Im using VSCode and it has a plugin that let's me view markdown as I write it and I have no issues with it rendering.

**Comment by vpetersson** [comment]
> > @Menmarin did you verify that this renders correct locally?
> 
> Yeah, Im using VSCode and it has a plugin that let's me view markdown as I write it and I have no issues with it rendering.

No, you can't just preview the markdown. You need to run `docker-compose up` and browse it to make sure it renders in Jekyll.

**Comment by Menmarin** [comment]
> 
> 
> > > @Menmarin did you verify that this renders correct locally?
> > 
> > 
> > Yeah, Im using VSCode and it has a plugin that let's me view markdown as I write it and I have no issues with it rendering.
> 
> No, you can't just preview the markdown. You need to run `docker-compose up` and browse it to make sure it renders in Jekyll.

I just ran it through docker-compose up and havent got any errors.

**Comment by vpetersson** [comment]
> I just ran it through docker-compose up and havent got any errors.

That's not sufficient. You need to make sure it renders properly too. I spotted an error, which is why i wanted you to find it. In any case, too much going back-and-forth on this. I will merge this PR and fix it myself.

**Comment by vpetersson** [comment]
@Menmarin see https://github.com/WoTTsecurity/wott-io/commit/3f4db98d690f24e3e234e83966eab50c53405e35 for the changes I made.

**Pull request merged**
