### PR TITLE
Fix pricing pricing to say per month rather than one-off. #76

### LINKED ISSUE #76: Fix pricing pricing to say per month rather than one-off.
I've added a temporary fix, but we need to make it nicer.

### PR DESCRIPTION
**Pull request by etf-yrm**
fix vertical align, desc text, remove padding in cost block, add fixed height for block
fixes problem #76 
closes #76 
Before visible:
Снимок экрана от 2019-07-11 16-58-24
After visible:
Снимок экрана от 2019-07-11 16-55-14

### CODE REVIEW

**Comment by vpetersson** [comment]
@etf-yrm No, what I meant was that the device count (such as 'Up to 250 devices') should be a block below. The price and per month should be in one block, and then space to the device block. We should also keep the device count in black.

**Comment by etf-yrm** [comment]
@vpetersson Ok

**Comment by etf-yrm** [comment]
Снимок экрана от 2019-07-11 17-32-14
it's fine?

**Comment by etf-yrm** [comment]
Снимок экрана от 2019-07-11 17-40-20
or this it's fine?

**Comment by vpetersson** [comment]
> Снимок экрана от 2019-07-11 17-40-20
> or this it's fine?

This one is the best one.

**Comment by etf-yrm** [comment]
this variant in commit

**Pull request merged**
