### PR TITLE
Implement and track pricing clicks #124

### LINKED ISSUE #124: Implement and track pricing clicks
(Blocked by [api#312](https://github.com/WoTTsecurity/api/issues/312))

We need to modify all links on the pricing page redirect to sign up page. What's also important is that we:

 * Pass on the GET parameter outlined in api#312 such that the plan is persistent
 * We fire off a GA event that includes all metadata, including *what* plan the user clicked on

### PR DESCRIPTION
**Pull request by etf-yrm**
fixes problem #124 
closes #124 

Add get in link[link?plan=number], add send to ga click info

### CODE REVIEW

**Comment by vpetersson** [comment]
@etf-yrm Is this in alignment with https://github.com/WoTTsecurity/api/pull/335?

**Comment by etf-yrm** [comment]
@vpetersson Yes

**Comment by etf-yrm** [comment]
> @etf-yrm Is this in alignment with [WoTTsecurity/api#335](https://github.com/WoTTsecurity/api/pull/335)?

@vpetersson Yes

**Comment by vpetersson** [comment]
@etf-yrm Can we please use more readable values than 1,2,3 for the type of plan? You should always be able to look at a variable and determine what it does/is without context. There is literally no upside in saving a few characters in 2019.

**Comment by etf-yrm** [comment]
> @etf-yrm Can we please use more readable values than 1,2,3 for the type of plan? You should always be able to look at a variable and determine what it does/is without context. There is literally no upside in saving a few characters in 2019.

@vpetersson Done in last commit

**Comment by vpetersson** [comment]
I think there's a misunderstanding here. I get where the 1..4 is coming from. My point was that they are not very useful in the context of Google Analytics. When you look at the events fired off to Google Analytics, you need to be able to look at them and understand what they are. 1..4 isn't very descriptive. It should be the actual plan as the event, such as 'Clicked Signup for Standard'.

**Pull request merged**
